language: java

sudo: false

install: "./.travis_install.sh"

script: mvn test

jdk:
  - oraclejdk7

notifications:
  email:
    - martin.monperrus@univ-lille1.fr
    - matias.sebastian.martinez@usi.ch


